### ISSUE TITLE
Investigate handling of "Off" commands for VibrationPattern messages

### ISSUE THREAD

**Issue by dmiklic** [larics/assisi-casu-beaglebone#53]
The "Off" command does not seem to be handled properly for VibrationPattern messages sent from the GUI.

**Comment by marselap** [comment]
It is not handled at all (i.e. "Unknown command"), at the moment only the "on" command exists for the vibration pattern. The "Off" only stops the vibrations as a Speaker command.

**Comment by marselap** [comment]
dcd1a91
