### ISSUE TITLE
Unable to run git commands on bbb-002

### ISSUE THREAD

**Issue by dmiklic** [larics/assisi-casu-beaglebone#7]
It seems to be [this issue] (http://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c).

**Comment by thaus88** [comment]
That's due to the date issue.

**Comment by dmiklic** [comment]
To fix, make sure that the Beaglebone is connected to the internet and run
```ntpdate -s ntp.ubuntu.com```
