### ISSUE TITLE
Peltier setpoint information is not reported correctly

### ISSUE THREAD

**Issue by dmiklic** [larics/assisi-casu-beaglebone#9]
Reported in larics/assisi-python#21. @thaus88 if you have the time to look at this before I do, please do so.

**Comment by thaus88** [comment]
It doesn't work because it's not implemented. The implementation includes modifications of both dsPIC firmware and beaglebone firmware which can be done when both boards are available for testing (e.g. next week).

**Comment by thaus88** [comment]
Implemented and tested.
